name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Deploy docs and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: git config -g user.email "tomibudis@gmail.com"
        run: git config -g user.name "tomibudis"
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install, build storybook
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy docs
        run: yarn deploy-docs
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release